### ISSUE TITLE
Corrupts Downloafs

### ISSUE THREAD

**Issue by DAMoran2022** [jmlag/OpenDownload3#3]
When downloading spinrite.exe from grc.com, OD3 ONLY downloads PART of the executable, resulting in a corrupted  program which won't run.

**Comment by DAMoran2022** [comment]
Have you **ABANDONED** this project???

**Comment by jmlag** [comment]
> Have you **ABANDONED** this project???

If you are unsatisfied with the software you may avail yourself of a full refund at any time.

Please provide a download link to reproduce the issue.
